# - Find ISMRMRRD
#   ISMRMRD_FOUND       - True if ISMRMRD found.
#   ISMRMRD_INCLUDE_DIR - where to find ismrmrd.h, etc.
#   ISMRMRD_LIBRARIES    - libismrmrd.so, etc.

MESSAGE("GADGETRON_HOME: $ENV{GADGETRON_HOME}")

FIND_PATH( ISMRMRD_INCLUDE_DIR ismrmrd.h
$ENV{GADGETRON_HOME}/include /usr/local/include)

FIND_LIBRARY( ISMRMRD_LIBRARIES
              NAMES "ismrmrd"
              PATHS  $ENV{GADGETRON_HOME}/lib /usr/local/lib)

INCLUDE( "FindPackageHandleStandardArgs" )
FIND_PACKAGE_HANDLE_STANDARD_ARGS( "Ismrmrd" DEFAULT_MSG ISMRMRD_INCLUDE_DIR ISMRMRD_LIBRARIES)

MARK_AS_ADVANCED( ISMRMRD_INCLUDE_DIR ISMRMRD_LIBRARIES)